export const ROUTES = {
  default: `/`,
  pageNotFound: `/404`,
  signIn: `/signIn`,
  signUp: `/signUp`,
  changePassword: `/change-password`,
  forgotPassword: `/forgot-password`,
  myAccount: `/myAccount`,
  buy: `/buy`,
  buyView: `/buy/view`,
  marketing: `/marketing`,
  marketingView: `/marketing/view`,
  contact: `/contact`,
  contactView: `/contact/view`,
  // buyView: (id: string) => `/buy/${id}`,
  userManagement: `/user-management`,
  userView: `/user-management/view-user`,
  userEdit: `/user-management/edit-user`,
  privacyPolicy: `/privacy-policy`,
  termsAndConditions: `/terms-and-conditions`,
  reactQueryDemo: `/react-query-demo`
};
